conda-forge/awscli2-feedstock

recipe/meta.yaml

across build, host, and run https://github.com/aws/aws-cli/blob/2.13.10/pyproject.toml#L42
add myself as a maintainer
Checklist

make awscrt requirements consistent

---

recipe/meta.yaml

Checklist
will go through and build each release that's come out since the feedstock was created

update to 2.13.11

---

recipe/meta.yaml

update to 2.13.12

---

recipe/meta.yaml

update to 2.13.13

---

recipe/meta.yaml

update to 2.13.14

---

recipe/meta.yaml

update to 2.13.15

---

recipe/meta.yaml

update to 2.13.16

---

recipe/meta.yaml

update to 2.13.17

---

recipe/meta.yaml

update to 2.13.18

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_aarch64_python3.10.____cpython.yaml
.ci_support/linux_aarch64_python3.11.____cpython.yaml
.ci_support/linux_aarch64_python3.8.____cpython.yaml
.ci_support/linux_aarch64_python3.9.____73_pypy.yaml
.ci_support/linux_aarch64_python3.9.____cpython.yaml
README.md
conda-forge.yml
recipe/meta.yaml

Build for linux-aarch64

---

recipe/meta.yaml

Checklist
just the first commit from #107, without the rerender

updated v2.15.51

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
recipe/meta.yaml

increase awscrt upper bound ref https://github.com/aws/aws-cli/commit/8874e0a8dc88291e08ec9cedc14471ccc4fe4f6c
Checklist
bot didn't open a pr for this release

update to v2.18.7

---

recipe/meta.yaml

for linter parsing error
v2 version of https://github.com/conda-forge/awscli-feedstock/pull/1726
Checklist

refactor duplicate script key

---

recipe/meta.yaml

there were 2 releases today, the bot will probably skip this one
Checklist

update to v2.22.11

---

conda-forge.yml
recipe/meta.yaml

Checklist
it's been over a year since we last tried, see if it works better by now

enable greyskull again

---

recipe/meta.yaml

bot will probably miss this version
Checklist

update to v2.14.16

---

recipe/meta.yaml

bot will probably miss this version
Checklist

update to v2.14.19

---

recipe/meta.yaml

Checklist
manual partial recreation with just one commit from these bot PR's
close #415 
close #416

updated v2.28.14

---

recipe/recipe.yaml

in line with changes the autotick bot proposed (#429)
Checklist

minor v2 format tweaks

---

recipe/recipe.yaml

updated v2.28.23
